# **Import Libraries**

In [12]:
import gymnasium as gym
import numpy as np
import tensorflow as tf
import time
import json
import os
import random
from collections import deque
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import clear_output

from modules.agents import DQNAgent
from modules.logger import EpisodeLogger
from modules.logger import save_params
import modules.rewards as rewards
import modules.processing as processing
import modules.figures as figures
import modules.networks as networks

ModuleNotFoundError: No module named 'yaml'

In [2]:
physical_devices = tf.config.list_physical_devices('GPU')

if physical_devices:
    print("GPU is available")
    print(physical_devices)
else:
    print("GPU is not available")

GPU is available
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# **Freeway Enviroment**

In [3]:
# create env with gymnasium (use ram, greyscale or rgb state)
env = gym.make(
    "ALE/Freeway-v5", # "Enviroment Variant"
    obs_type="ram", # ram, grescale, rgb
    render_mode="rgb_array", # rgb_array or human
    difficulty = 0, # [0, 1]
    mode = 0 # [0]
    ) 

env.reset()
print(env.step(0))
print(f"State Frame Size: {env.observation_space}")
print(f"Number Of Actions: {env.action_space.n}")

actions_space = possible_actions = np.array(np.identity(env.action_space.n,dtype=int).tolist())
print(f"Possible Actions: \n {actions_space}")

env.reset()
observation = env.step(1)
print(f"Obervation: \n {observation[0]}")
print(observation[0].shape)

(array([  0,   4, 132,   0,  15,  15,   0, 255,  74,  30,  12,   6,   0,
         8,   6,   6, 255, 255,   7,   7,  26,   0, 255,  80,  64,  48,
        32,  16, 144, 160, 176, 192, 208,   2,   1,   0,   1,   0,   0,
         0,   2,   0,   1,  80,  80,  80,  64,  48,  10, 234, 234, 218,
       218, 122, 138,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,
        80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  26,
       216,  68, 136,  36, 130,  74,  18, 220,  66, 189, 247, 122, 247,
       122, 247,  80, 247,  80, 247,   0, 247,   0, 247,   0,   0,   0,
         0,   0,   0,   0,   1,   1,   1,   2,   3, 156, 158, 158, 159,
       159,   0,  16,   5,   1,  80, 255,  87, 246,  75, 244], dtype=uint8), 0.0, False, False, {'lives': 0, 'episode_frame_number': 4, 'frame_number': 4})
State Frame Size: Box(0, 255, (128,), uint8)
Number Of Actions: 3
Possible Actions: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Obervation: 
 [  0   4 132   0  14  15   0 255  74  30  12   6   0   8  10   6 25

# **Hyperparameter**

In [4]:
"""
MODEL_VERSION = "v_1"

# GAME PARAMETER
EVIROMENT_VARIANT = "ALE/Freeway-v5"
DIFFICULTY = 0
MODE = 0

env = gym.make(EVIROMENT_VARIANT, obs_type="ram", difficulty = 0, mode = 0) 

# MODEL Hyperparameters
STATE_SIZE = env.observation_space.shape[0]
ACTIONS_SIZE = env.action_space.n
ACTIONS = list(range(0, ACTIONS_SIZE))
LEARNING_RATE = 0.001 # Learning Rate (alpha)

# AGENT Hyperparameters (epsilon greedy strategy)
EPSILON = 0.99
EPSILON_MIN = 0.01 # EPSELON value where exploreation stops
EPSILON_DECAY_RATE = 0.9995 # the higher the longer the exploreation takes (Linear Decay: EPSELON * DECAY_RATE)
GAMMA = 0.99 # Discounting rate (lower -> agent thinks more long term)

# TRAINING Hyperparameters
RENDER_INTERVAL = 100 # Intervall when the game is rendered
TOTAL_EPISODES = 1000
REPLAY_INTERVAL = 4 # Replay every x steps (retrain model) 
MINI_BATCHES_REPLAY = 16
REPLAY_BUFFER_MEMORY = 200000
MINIMUM_REPLAY_HISTORY = 10000
AVERAGE_WINDOW = 10
UPDATE_TARGET_MODEL_FREQUENCY = 5 # Intevall of episodes the target model is updated
MODEL_SAVE_INTERVALL = 10 # Intervall in which the target model is saved
"""

'\nMODEL_VERSION = "v_1"\n\n# GAME PARAMETER\nEVIROMENT_VARIANT = "ALE/Freeway-v5"\nDIFFICULTY = 0\nMODE = 0\n\nenv = gym.make(EVIROMENT_VARIANT, obs_type="ram", difficulty = 0, mode = 0) \n\n# MODEL Hyperparameters\nSTATE_SIZE = env.observation_space.shape[0]\nACTIONS_SIZE = env.action_space.n\nACTIONS = list(range(0, ACTIONS_SIZE))\nLEARNING_RATE = 0.001 # Learning Rate (alpha)\n\n# AGENT Hyperparameters (epsilon greedy strategy)\nEPSILON = 0.99\nEPSILON_MIN = 0.01 # EPSELON value where exploreation stops\nEPSILON_DECAY_RATE = 0.9995 # the higher the longer the exploreation takes (Linear Decay: EPSELON * DECAY_RATE)\nGAMMA = 0.99 # Discounting rate (lower -> agent thinks more long term)\n\n# TRAINING Hyperparameters\nRENDER_INTERVAL = 100 # Intervall when the game is rendered\nTOTAL_EPISODES = 1000\nREPLAY_INTERVAL = 4 # Replay every x steps (retrain model) \nMINI_BATCHES_REPLAY = 16\nREPLAY_BUFFER_MEMORY = 200000\nMINIMUM_REPLAY_HISTORY = 10000\nAVERAGE_WINDOW = 10\nUPDATE_TARGET_MO

In [5]:
# change parameters here
params = {
    "MODEL_VERSION": "v_1",
    "EVIROMENT_VARIANT": "ALE/Freeway-v5",
    "DIFFICULTY": 0,
    "MODE": 0,
    "obs_type": "ram",
    "STATE_SIZE": env.observation_space.shape[0], 
    "ACTIONS_SIZE": env.action_space.n,
    "ACTIONS": list(range(0, env.action_space.n)),
    "LEARNING_RATE": 0.001, # Learning Rate (alpha)
    "EPSILON": 0.99,
    "EPSILON_MIN": 0.01, # EPSELON value where exploreation stops
    "EPSILON_DECAY_RATE": 0.9995, # the higher the longer the exploreation takes (Linear Decay: EPSELON * DECAY_RATE)
    "GAMMA": 0.99, # Discounting rate (lower -> agent thinks more long term)
    "RENDER_INTERVAL": 100, # Intervall when the game is rendered
    "TOTAL_EPISODES": 1000,
    "REPLAY_INTERVAL": 4, # Replay every x steps (retrain model) 
    "MINI_BATCHES_REPLAY": 16,
    "REPLAY_BUFFER_MEMORY": 200000,
    "MINIMUM_REPLAY_HISTORY": 10000,
    "AVERAGE_WINDOW": 10,
    "UPDATE_TARGET_MODEL_FREQUENCY": 5, # Intevall of episodes the target model is updated
    "MODEL_SAVE_INTERVALL": 10 # Intervall in which the target model is saved
}

In [6]:
MODEL_VERSION = params["MODEL_VERSION"]
EVIROMENT_VARIANT = params["EVIROMENT_VARIANT"]
obs_type = params["obs_type"]
DIFFICULTY = params["DIFFICULTY"]
MODE = params["MODE"]
STATE_SIZE = params["STATE_SIZE"]
ACTIONS_SIZE = params["ACTIONS_SIZE"]
ACTIONS = params["ACTIONS"]
LEARNING_RATE = params["LEARNING_RATE"]
EPSILON = params["EPSILON"]
EPSILON_MIN = params["EPSILON_MIN"]
EPSILON_DECAY_RATE = params["EPSILON_DECAY_RATE"]
GAMMA = params["GAMMA"]
RENDER_INTERVAL = params["RENDER_INTERVAL"]
TOTAL_EPISODES = params["TOTAL_EPISODES"]
REPLAY_INTERVAL = params["REPLAY_INTERVAL"]
MINI_BATCHES_REPLAY = params["MINI_BATCHES_REPLAY"]
REPLAY_BUFFER_MEMORY = params["REPLAY_BUFFER_MEMORY"]
MINIMUM_REPLAY_HISTORY = params["MINIMUM_REPLAY_HISTORY"]
AVERAGE_WINDOW = params["AVERAGE_WINDOW"]
UPDATE_TARGET_MODEL_FREQUENCY = params["UPDATE_TARGET_MODEL_FREQUENCY"]
MODEL_SAVE_INTERVALL = params["MODEL_SAVE_INTERVALL"]

In [9]:
save_params(params, f"parameters/{MODEL_VERSION}/", MODEL_VERSION)

# **Init Agent and Logger**

In [ ]:
agent = DQNAgent(REPLAY_BUFFER_MEMORY, MINI_BATCHES_REPLAY, EPSILON, ACTIONS_SIZE, GAMMA, EPSILON_MIN, EPSILON_DECAY_RATE, LEARNING_RATE)
logger = EpisodeLogger(log_files_dir=f"logs/{MODEL_VERSION}/")

# **Fill Replay Buffer**

In [ ]:
env = gym.make(EVIROMENT_VARIANT, obs_type="ram", difficulty=DIFFICULTY, mode=MODE) 

state = env.reset()[0]
preprocessed_state = processing.preprocess_ram(state)
total_reward = 0
average_rewards = []
rewards_per_episode = []
distance_per_episode = []

with tqdm(total=MINIMUM_REPLAY_HISTORY) as pbar:
    while len(agent.memory.buffer) < MINIMUM_REPLAY_HISTORY:
        # take random action action
        action = random.randint(0, ACTIONS_SIZE - 1)
        next_state, game_reward, game_done, game_loss_of_live, game_info = env.step(action)

        y_pos = env.ale.getRAM()[14] // 3
        crashed = 1 if env.ale.getRAM()[16] != 255 else 0 # RAM(16) =:= Collision Lane

        next_state_preprocessed = processing.preprocess_ram(next_state)

        # update reward
        total_reward, gained_reward = rewards.action_based_reward(total_reward, crashed, action, y_pos, game_reward)

        # store action infromation in memory
        agent.remember(preprocessed_state, next_state_preprocessed, action, gained_reward, crashed)

        # set the next state to the current state
        preprocessed_state = next_state_preprocessed
        pbar.update(len(agent.memory.buffer) - pbar.n)

# **Training**

In [ ]:
%matplotlib qt

for episode in range(TOTAL_EPISODES):
    print(f"EPISODE: {episode}")
    # create env (human to render game and see actions)
    if episode % RENDER_INTERVAL == 0 and episode != 0:
        env = gym.make(EVIROMENT_VARIANT, obs_type="ram", render_mode="human", difficulty=DIFFICULTY, mode=MODE) 
    else:
        env = gym.make(EVIROMENT_VARIANT, obs_type="ram", difficulty=DIFFICULTY, mode=MODE) 
        
    state = env.reset()[0]
    preprocessed_state = processing.preprocess_ram(state)

    # reset episode variables
    step_count = 0
    distance_before = 0
    total_reward = 0

    # initilize episode stack
    #stacked_array_state, STACKED_FRAMES = process.stack_frames(STACKED_FRAMES, preprocessed_state, is_new_episode, STATE_SIZE, STACKED_FRAMES_SIZE)
    
    while True:
        # update step_count
        step_count += 1

        # Predict action
        action = agent.predict_action(preprocessed_state)
        next_state, game_reward, game_done, game_loss_of_live, game_info = env.step(action)

        y_pos = env.ale.getRAM()[14] // 3
        crashed = 1 if env.ale.getRAM()[16] != 255 else 0 # RAM(16) =:= Collision Lane

        next_state_preprocessed = processing.preprocess_ram(next_state)

        # update reward
        total_reward, gained_reward = rewards.action_based_reward(total_reward, crashed, action, y_pos, game_reward)

        # store action infromation in memory
        agent.remember(preprocessed_state, next_state_preprocessed, action, gained_reward, crashed)

        # set the next state to the current state
        preprocessed_state = next_state_preprocessed

        # Do Replay
        agent.replay()

        # END EPISODE IF CHICKEN COLLIDES
        if crashed == 1 or game_reward == 1:
            # clear output of cell for every new episode
            clear_output(wait=True)

            # update ntework
            agent.update_target_model()
            
            rewards_per_episode.append(total_reward)
            distance_per_episode.append(y_pos)

            if len(rewards_per_episode) >= AVERAGE_WINDOW:
                moving_average = np.mean(rewards_per_episode[-AVERAGE_WINDOW:])
            else:
                moving_average = np.mean(rewards_per_episode)
            average_rewards.append(moving_average)

            step_text = f"Episode: {episode}/{TOTAL_EPISODES}, Total Reward: {total_reward}, Moving AVG. Reward: {moving_average}, Distance: {y_pos}, Epsilon: {agent.EPSILON:.2}"
            
            figures.reward_plot(rewards_per_episode, average_rewards, dir=f"figures/{MODEL_VERSION}/")
            figures.distance_plot(distance_per_episode, dir=f"figures/{MODEL_VERSION}/")

            time.sleep(0.1)

            print(step_text)
            if episode % UPDATE_TARGET_MODEL_FREQUENCY == 0:
                agent.update_target_model()

            logger.log_episode(total_reward, moving_average, agent.EPSILON, y_pos)
            networks.save_model(agent.target_model, episode, MODEL_SAVE_INTERVALL, dir=f"models/{MODEL_VERSION}/")
            break

        is_new_episode = False
        distance_before = y_pos
